server:
  port: ${PORT:0}

spring:
  application:
    name: address
  cloud:
    config:
      uri: http://localhost:8888
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
  logging:
    file: logs/address/logging.log
    pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
    level:
      org.springframework.web: DEBUG
      com.dsfire.service2BS.controllers: DEBUG
      org.hibernate: DEBUG

eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true
