server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  profiles:
    active: native

my:
  property: myvalue

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true
